description: "Pattern matcher for web security testing"
tags:
  - pattern-matching
  - filtering
  - web
  - xss
  - lfi
  - sqli
  - rce
  - ssrf
  - ssti
  - idor
  - url_redirect
run_command: "gf"
accepts_stdin: true