name: "Httpx"
run_command: "~/go/bin/httpx"
description: "Probe and discover alive web services from subdomains."
documentation: "https://github.com/projectdiscovery/httpx"
tags:
  - web
  - reconnaissance
accepts_stdin: true
