# tools/paramspider/config.yaml
description: "Parameter discovery through source code analysis"
tags:
  - parameter-discovery
  - web
  - discovery
run_command: "paramspider"  # Create results directory before running
accepts_stdin: false